// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:developer';
import 'dart:isolate' as isolate;

import 'package:test/test.dart';
import 'package:vm_service/vm_service.dart';

import 'common/service_test_common.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart pkg/vm_service/test/reload_sources_test_common.dart
//
const LINE_A = 26;
const LINE_B = 56;
// AUTOGENERATED END

const isolatesToSpawn = 2;

Future<void> testeeMain() async {
  debugger(); // LINE_A.
  print('1');
  while (getCurrentPhase() == 0) {}
  print('2');
  final runningPort = isolate.ReceivePort();
  final runningSendPort = runningPort.sendPort;
  for (var i = 0; i < isolatesToSpawn; i++) {
    isolate.Isolate.run(() async {
      print('isolate $i running');
      var shouldStop = false;
      final stopPort = isolate.ReceivePort();
      final stopSendPort = stopPort.sendPort;
      stopPort.listen((_) {
        shouldStop = true;
      });
      runningSendPort.send(stopSendPort);
      while (!shouldStop) {
        await Future.delayed(const Duration(milliseconds: 100));
      }
      return true;
    }).then(
      (_) {
        print('isolate $i exited');
      },
      onError: (e) {
        print('isolate $i exited with error: $e');
      },
    ).ignore();
  }
  final running = (await runningPort.take(2).toList()).cast<isolate.SendPort>();
  debugger(); // LINE_B
  while (getCurrentPhase() == 1) {}
  for (var port in running) {
    port.send(null);
  }
}

var currentPhase = 0;

@pragma('vm:never-inline')
int getCurrentPhase() {
  return currentPhase;
}

int nextPhase() {
  currentPhase++;
  return currentPhase;
}

Future<void> isolateIsRunning(VmService service, IsolateRef isolateRef) async {
  final isolate = await service.getIsolate(isolateRef.id!);
  final pauseEvent = isolate.pauseEvent;
  final isPaused = pauseEvent == null
      ? false
      : isolate.pauseEvent!.kind != EventKind.kResume;
  final topFrame = pauseEvent?.topFrame;
  expect(!isPaused && topFrame != null, true);
}

Future<void> expectBreakpointValid(
  VmService service,
  IsolateRef isolateRef,
  Breakpoint bp,
) async {
  await expectLater(
    service.getObject(isolateRef.id!, bp.id!),
    completion(isA<Breakpoint>()),
  );
}

Future<void> expectBreakpointInvalid<E>(
  VmService service,
  IsolateRef isolateRef,
  Breakpoint bp,
) async {
  await expectLater(
    service.getObject(isolateRef.id!, bpt.id!),
    throwsA(isA<E>()),
  );
}

Future<void> expectBreakpointLine(
  VmService service,
  IsolateRef isolateRef,
  Breakpoint bp,
  int expectedLine,
) async {
  final (_, (line, _)) = await bp.getLocation(service, isolateRef);
  expect(line, equals(expectedLine));
}

late Breakpoint bpt;

final reloadSourcesTests = <IsolateTest>[
  // Stopped at 'debugger' statement.
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_A),
  // Reload sources and request to pause post reload. The pause request will be
  // ignored because we are already paused at a breakpoint.
  reloadSources(pause: true),
  // Ensure that we are still stopped at a breakpoint.
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_A),
  // Resume the isolate into the while loop.
  resumeIsolate,
  // Verify that it is running.
  isolateIsRunning,
  // Reload sources and request to pause post reload. The pause request will
  // be respected because we are not already paused.
  reloadSources(pause: true),
  // Ensure that we are paused post reload request.
  hasStoppedPostRequest,
  // Resume the isolate.
  resumeIsolate,
  // Verify that it is running.
  isolateIsRunning,
  // Reload sources and do not request to pause post reload.
  reloadSources(),
  // Verify that it is running.
  isolateIsRunning,
  // Set a breakpoint.
  (VmService service, IsolateRef isolateRef) async {
    bpt = await service.addBreakpointWithScriptUri(
      isolateRef.id!,
      'reload_sources_test_common.dart',
      LINE_A,
    );
    expect(bpt.enabled, true);
    await expectBreakpointValid(service, isolateRef, bpt);
  },
  (VmService service, IsolateRef isolateRef) async {
    // Check that no-op reload does not apply breakpoint updates.
    //
    // Note: we don't actually change the source code here so reload without
    // force will be a no-op.
    var result = await service.reloadSources(
      isolateRef.id!,
      breakpointsUpdates: [
        BreakpointsUpdate(
          isolateId: 'foo/${isolateRef.id!.split('/')[1]}',
          toRemove: [
            bpt.id!,
          ],
        ),
      ],
    );
    expect(result.success, isTrue);
    expect(result.breakpointsUpdateReports, isNull);

    // Case 1: check that invalid isolate id is handled properly.
    result = await service.reloadSources(
      isolateRef.id!,
      force: true, // We don't need
      breakpointsUpdates: [
        BreakpointsUpdate(
          isolateId: 'foo/${isolateRef.id!.split('/')[1]}',
          toRemove: [
            bpt.id!,
          ],
        ),
      ],
    );
    expect(result.success, isTrue);
    expect(
      result.breakpointsUpdateReports,
      equals([isA<BreakpointsUpdateFailure>()]),
    );

    // Case 2: check that valid breakpoint is correctly removed and invalid
    // breakpoint results in an error. Check that new breakpoint is created
    // correctly using `toAdd`.
    result = await service.reloadSources(
      isolateRef.id!,
      force: true,
      breakpointsUpdates: [
        BreakpointsUpdate(
          isolateId: isolateRef.id!,
          toRemove: [
            'breakpoints/invalid',
            bpt.id!,
          ],
          toAdd: [
            BreakpointLocation(
              scriptUri: 'reload_sources_test_common.dart',
              line: LINE_A + 1,
            ),
            BreakpointLocation(
              scriptUri: 'reload_sources_test_common.dart',
              line: 1000,
            ),
          ],
        ),
      ],
    );
    expect(result.success, isTrue);
    expect(
      result.breakpointsUpdateReports,
      equals([isA<BreakpointsUpdateReport>()]),
    );
    final [BreakpointsUpdateReport updateReport] =
        result.breakpointsUpdateReports!;
    expect(
      updateReport.removals,
      equals([
        isA<BreakpointsUpdateFailure>(),
        isA<Success>(),
      ]),
    );
    expect(
      updateReport.additions,
      equals([
        isA<Breakpoint>(),
        isA<BreakpointsUpdateFailure>(),
      ]),
    );
    final addedBp = updateReport.additions![0];

    // Check that original breakpoint does not exist and the newly added
    // breakpoint exists.
    await expectBreakpointInvalid<SentinelException>(service, isolateRef, bpt);
    await expectBreakpointValid(service, isolateRef, addedBp);
    bpt = addedBp;

    await service.pause(isolateRef.id!);
  },
  hasPausedOnInterrupt,
  (VmService service, IsolateRef isolateRef) async {
    await service.evaluateInFrame(isolateRef.id!, 0, 'nextPhase()');
  },
  resumeIsolate,
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_B),
  (VmService service, IsolateRef isolateRef) async {
    // Find other isolates which were spawned by the process.
    final vm = await service.getVM();
    final otherIsolatesInGroup = vm.isolates!
        .where(
          (i) =>
              i.id != isolateRef.id &&
              i.isolateGroupId == isolateRef.isolateGroupId,
        )
        .toList(growable: false);
    expect(otherIsolatesInGroup.length, equals(isolatesToSpawn));

    // Check that breakpoint exists in the main isolate and does not
    // automatically exist in other isolates.
    await expectBreakpointValid(service, isolateRef, bpt);
    for (final otherIsolateRef in otherIsolatesInGroup) {
      await expectBreakpointInvalid<RPCError>(service, otherIsolateRef, bpt);
    }

    // Add breakpoints to both isolates.
    final bpts = await [
      for (var otherIsolateRef in otherIsolatesInGroup)
        service.addBreakpointWithScriptUri(
          otherIsolateRef.id!,
          'reload_sources_test_common.dart',
          LINE_A,
        ),
    ].wait;
    expect(bpts, everyElement(isA<Breakpoint>()));

    final breakpointEvents = [];
    final subscription = service.onDebugEvent.listen((data) {
      switch (data.kind) {
        case EventKind.kBreakpointAdded:
        case EventKind.kBreakpointRemoved:
          breakpointEvents.add(data);
      }
    });
    await service.streamListen(EventStreams.kDebug);

    // Reload isolate group (via the first isolate) and apply updates.
    final result = await service.reloadSources(
      isolateRef.id!,
      force: true,
      breakpointsUpdates: [
        // In the main isolate remove breakpoint and place a new one.
        BreakpointsUpdate(
          isolateId: isolateRef.id!,
          toRemove: [
            bpt.id!,
          ],
          toAdd: [
            BreakpointLocation(
              scriptUri: 'reload_sources_test_common.dart',
              line: LINE_A + 2,
            ),
          ],
        ),

        // In the first child isolate remove breakpoint and do not add more.
        BreakpointsUpdate(
          isolateId: otherIsolatesInGroup[0].id!,
          toRemove: [
            bpts[0].id!,
          ],
          toAdd: [],
        ),

        // In the second child isolate keep breakpoint and add more.
        BreakpointsUpdate(
          isolateId: otherIsolatesInGroup[1].id!,
          toRemove: [],
          toAdd: [
            BreakpointLocation(
              scriptUri: 'reload_sources_test_common.dart',
              line: LINE_A + 3,
            ),
          ],
        ),
      ],
    );

    await service.streamCancel(EventStreams.kDebug);
    await subscription.cancel();

    expect(result.success, isTrue);
    expect(result.breakpointsUpdateReports?.length, equals(3));
    expect(
      result.breakpointsUpdateReports,
      everyElement(isA<BreakpointsUpdateReport>()),
    );

    // In the first isolate we removed breakpoint and added one more.
    final [
      BreakpointsUpdateReport updates0,
      BreakpointsUpdateReport updates1,
      BreakpointsUpdateReport updates2
    ] = result.breakpointsUpdateReports!;
    expect(updates0.removals, equals([isA<Success>()]));
    await expectBreakpointInvalid<SentinelException>(service, isolateRef, bpt);
    expect(updates0.additions, equals([isA<Breakpoint>()]));
    final [Breakpoint bp0] = updates0.additions!;
    await expectBreakpointLine(service, isolateRef, bp0, LINE_A + 2);

    // In the second isolate we removed breakpoint and did not add more.
    expect(updates1.removals, equals([isA<Success>()]));
    await expectBreakpointInvalid<RPCError>(
      service,
      otherIsolatesInGroup[0],
      bpts[0],
    );
    expect(updates1.additions, isEmpty);

    // In the third isolate we kept breakpoint and added one more.
    await expectBreakpointValid(service, otherIsolatesInGroup[1], bpts[1]);
    expect(updates2.removals, isEmpty);
    expect(updates2.additions, equals([isA<Breakpoint>()]));
    final [Breakpoint bp1] = updates2.additions!;
    await expectBreakpointLine(service, isolateRef, bp1, LINE_A + 3);

    expect(breakpointEvents.length, equals(4));
    expect(
      {
        for (var e in breakpointEvents)
          (e.kind, e.isolate!.id, e.breakpoint!.id),
      },
      equals({
        (EventKind.kBreakpointRemoved, isolateRef.id, bpt.id),
        (EventKind.kBreakpointAdded, isolateRef.id, bp0.id),
        (EventKind.kBreakpointRemoved, otherIsolatesInGroup[0].id, bpts[0].id),
        (EventKind.kBreakpointAdded, otherIsolatesInGroup[1].id, bp1.id),
      }),
    );
  },
  resumeIsolate,
];
